// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rolbhozqvenvhcvclaqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbGJob3pxdmVudmhjdmNsYXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNDE1MzIsImV4cCI6MjA1NjgxNzUzMn0.u7WEpjGTArtKRwwu7YUCINBKYXu-2yLR1k96NMKQrTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);